config/.eslintrc.js, config/tsconfig.json
A few minor adjustments to make writing non-trivial components in the SDK possible. Disabling "strictNullChecks" is temporary until we can fix things up in Web.
=> fix: compiler/lint rules to work with Web

lib/index.ejs
Load the viewer in debug mode, for both enhanced logging and loading of development libraries for dependencies like react.
=> fix: Add debug url param to webviewer loading url

lib/index.ejs
Allows forwarding of the `locale` URL param to Web to test the rendering of different locales. 
For example to test German, change the url from:
```
http://localhost:3000
```
to:
```
http://localhost:3000/?locale=de
```
=> feat: forward locale url param to Web

lib/index.ejs
This adds logic to proxy postMessage events in both directions through our wrapper `iframe`. We're also proxying URL params through as well to enable things like `isEmbedded=true`, while simplifying our existing `locale` support.
This also fixes an issue where the React devtools hook would break after a reload of the viewer triggered via webpack.
=> fix: proxy query params and postMessage events

TODO.md, package.json, template/package.json, template/src/components/PointsOfInterest/PointsOfInterestModel.ts, template/src/index.ts
This fixes the SDK sample to use the new command registration pattern recently introduced in 5.7.
I also temporarily have both the SDK and the template pointing at a beta version of @vertigis/web just to get things working again. We'll need to update it to the final version once released. To test, make sure to set the `VIEWER_URL` environment variable to `VIEWER_URL=https://apps-staging.geocortex.com/webviewer`.
=> fix: Update sample to use new command registration in 5.7

config/webpack.config.js
Fixes webpack loader resolution when multiple versions of a given loader exist in the project. This ensures that the loader is resolved relative to the SDK, so the version referenced by the SDK is used instead.
=> fix: webpack loader resolution

.github/workflows/ci-cd.yml, .prettierrc, bin/vertigis-web-sdk.js, config/webpack.config.js, lib/index.ejs, package.json, scripts/create.js, scripts/start.js, test/index.js
Adds a set of basic smoke tests to validate the core functionality works as expected. These will run as part of the CI build.
I changed the CLI to require the appropriate script module (`create`, `build`, ...) instead of spawning a new process. This fixed some issues with process cleanup when invoking the CLI via the tests. The `start` script specifically would remain running even after killing the spawned process that ran the CLI, which meant that webpack-dev-server continued to run after the test had finished in some circumstances.
=> test: add smoke tests

config/.eslintrc.js
After enabling ESLint checking in the samples repo, I felt that these rules i've disabled here were too strict, and are likely to annoy developers.
=> fix: disable overly strict ESLint rules

scripts/start.js
Adds a new `OPEN_PAGE` environment variable to control the default page that the browser opens to. This lets us support the [iframe example](https://github.com/geocortex/vertigis-web-samples/tree/92b4ba2c1b1e7483e3d322689e4615f28e2046ee/samples/iframe).
=> feat: add OPEN_PAGE environment variable

config/webpack.config.js, package.json
This adds [`url-loader`](https://github.com/webpack-contrib/url-loader) to our webpack config to support importing static assets such as images and fonts. These assets will be inlined as data URIs as we only support a single chunk to be emitted.
This makes us more compatible with 3rd party libraries, such as Mapillary that uses `url()` statements in their CSS to reference relative SVGs in their package.
=> feat: add url-loader to webpack config

config/webpack.config.js, scripts/build.js
Disable [webpack performance hints](https://v4.webpack.js.org/configuration/performance/) as the hints are generally not actionable by the developer as we only allow one chunk to be emitted.
=> fix: disable webpack performance hints

package.json, template/src/components/PointsOfInterest/PointsOfInterestModel.ts
update PointsOfInterestModel to use the framework MapModel over the arcgis-extension's MapExtension.
=> fix: Update PointsOfInterestModel to reference framework MapModel

README.md, bin/vertigis-web-sdk.js, package.json, scripts/upgrade.js, template/package.json
This PR adds a new script to the SDK: `npm run upgrade`. When run within the context of a custom library created by the SDK, it will automatically upgrade its package.json to point at the latest versions of Web and the Web SDK. It will also explicitly add/update any of Web's dependencies as direct dependencies of the project. Without this, VS Code autocomplete and intellisense don't work for things like arcgis-extensions or react.
=> feat: Adding a script for updating package.json dev dependencies

config/paths.js
Adds a BUILD_ENTRY_POINT environment variable that allows you to override the default "src/index" file of the project. This supports use cases where a single project contains multiple apps for which separate builds should be created.
To use this you might add something like this to your package.json (or use cross-env):
```
"build": "vertigis-web-sdk build",
"build:app2": "set BUILD_ENTRY_POINT=src/index.app2&& npm run build"
```
=> feat: add BUILD_ENTRY_POINT environment variable

.eslintrc.cjs, .npmrc, .prettierignore, .prettierrc, .vscode/launch.json, .vscode/settings.json, README.md, bin/vertigis-web-sdk.js, config/.eslintrc/README.md, config/.eslintrc/index.js, config/.eslintrc/package.json, config/paths.js, config/webpack.config.js, package-lock.json, package.json, scripts/build.js, scripts/create.js, scripts/start.js, scripts/upgrade.js, template/README.md, template/package.json, template/tsconfig.json, test/index.js, tsconfig.json
This PR performs some housekeeping. There is no new functionality for consumers. It:
- Updates many dependencies to the latest versions
- Converts the SDK to `"type": "module"`, i.e. uses ES modules instead of common JS. Many dependencies are now ESM only in their latest versions, making it hard to stay up to date with cjs code.
- Pins all dev dependencies, and narrows public dependency version ranges to patch versions only. In many cases, a minor version release of e.g. TypeScript, eslint, or webpack can introduce compile/lint errors in code that previously worked. We want to make sure that consumers are using versions of these packages that we have actually tested.
- Adds a package lock to facilitate npm audit.
- Adds checks for minimum versions of Node and npm that we support. We use …
=> chore: Update project to ESM and narrow dependencies

.github/workflows/ci-cd.yml, package-lock.json, package.json
This PR upgrades the SDK to require Node 16. While it could still work with 14, we will no longer be testing it with Node 14, and so cannot officially support it.
=> chore: Upgrading to Node 16 / npm 8.

config/webpack.config.js, lib/index.ejs
Adds a ADDITIONAL_LIBS environment variable that allows you to load additional Studio Web SDK libraries. So far when developing a library with the Studio Web SDK, the local dev server only allowed working with the library you were developing. With help of the ADDITIONAL_LIBS environment variable you can configure your Studio Web SDK project to inject other external Studio Web SDK libraries. 
To use this you might add something like this to your package.json (or use cross-env):
"start": "vertigis-web-sdk start",
"start:app-with-additional-lib": "set ADDITIONAL_LIBS=['https://yourwebsite.com/yourlib.js']&& npm run start"
=> feat: add ADDITIONAL_LIBS environment variable

README.md, package-lock.json, package.json, scripts/build.js, scripts/create.js, template/README.md
This PR updates obsolete Geocortex URLs and replaces them with their VertiGIS equivalents. 
There is also a problem with releases on GitHub at the moment that is highly likely being caused by the redirect from the old GitHub org.
=> chore: Replace outdated Geocortex URLs with VertiGIS URLs

.github/workflows/ci-cd.yml
This PR bumps some out-of-date versions of GitHub actions in our CI configuration.
The commit has "fix: ..." even though  "chore: ..."  would be more appropriate since the previous fix accidentally omitted it, preventing a release.
=> fix: Updating CI actions to versions compatible with Node 20

package-lock.json, package.json, scripts/build.js, scripts/create.js, template/package.json, template/src/components/PointsOfInterest/PointOfInterest.tsx, tsconfig.json
- Fixed the broken help urls in the `create` and `build` scripts.
- Updated a couple of packages to remove warnings.
- Updated typescript in the sample template.
- Changed a `div` to a `Box` in the sample template.
- Fixed linter not running on sample template.
=> fix: broken urls in scripts, other misc items

config/tsconfig.json
These shouldn't have been added as they are a potential breaking change for existing code.
=> fix: remove new tsconfig rules that throw errors

README.md
fix: update documentation URLs to use correct domain
Several documentation links were pointing to the an incorrect domain (developers.vertigis.com). 
Updated these to use the current domain (developers.vertigisstudio.com) to ensure users 
can access the correct documentation resources.
Changes:
- Updated deployment guide link
- Updated Developer Center links
- Updated SDK documentation link
=> fix: update links in README for VertiGIS Studio Developer Center documentation
